#!/usr/bin/env python3
"""Step C: Read B1 (region_stats.json) and B2 (monthly_trend.json), produce final report."""

import json
import time
from datetime import datetime
from pathlib import Path
from typing import Any

INPUT_DIR = Path(__file__).parent
REGION_STATS_PATH = INPUT_DIR / "region_stats.json"
MONTHLY_TREND_PATH = INPUT_DIR / "monthly_trend.json"
REPORT_PATH = INPUT_DIR / "final_report.md"


def load_json(path: Path) -> dict[str, Any]:
    """Load a JSON file."""
    with open(path, "r") as f:
        return json.load(f)


def generate_report(region_stats: dict[str, dict[str, float]],
                    monthly_trend: dict[str, dict[str, float]]) -> str:
    """Generate a consolidated final report in Markdown."""
    lines: list[str] = [
        "# Sales Data Analysis Report\n",
        "Auto-generated by AutoGoo DAG Test Pipeline\n",
        "---\n",
    ]

    # --- Overview ---
    total_orders: int = sum(s["count"] for s in region_stats.values())
    total_sales: float = sum(s["sum"] for s in region_stats.values())
    lines.append("## Overview\n")
    lines.append(f"- **Total Orders**: {total_orders}")
    lines.append(f"- **Total Sales**: ${total_sales:.2f}")
    lines.append(f"- **Regions**: {', '.join(sorted(region_stats.keys()))}")
    lines.append(f"- **Period**: {min(monthly_trend.keys())} ~ {max(monthly_trend.keys())}\n")
    lines.append("---\n")

    # --- Region Statistics ---
    lines.append("## Region Statistics\n")
    lines.append("| Region | Orders | Total Sales | Avg Order | Min | Max |")
    lines.append("|--------|--------|-------------|-----------|-----|-----|")
    for region, s in sorted(region_stats.items()):
        lines.append(
            f"| {region} | {s['count']} | ${s['sum']:.2f} | "
            f"${s['mean']:.2f} | ${s['min']:.2f} | ${s['max']:.2f} |"
        )
    lines.append("")

    # --- Monthly Trend ---
    lines.append("## Monthly Sales Trend\n")
    lines.append("| Month | Orders | Total Sales | Avg Sale |")
    lines.append("|-------|--------|-------------|----------|")
    for month, t in monthly_trend.items():
        lines.append(
            f"| {month} | {t['order_count']} | "
            f"${t['total_sales']:.2f} | ${t['average_sale']:.2f} |"
        )
    lines.append("")

    # --- Top months ---
    lines.append("## Highlights\n")
    top_month: str = max(monthly_trend, key=lambda m: monthly_trend[m]["total_sales"])
    top_region: str = max(region_stats, key=lambda r: region_stats[r]["sum"])
    lines.append(f"- **Best month**: {top_month} (${monthly_trend[top_month]['total_sales']:.2f})")
    lines.append(f"- **Top region**: {top_region} (${region_stats[top_region]['sum']:.2f})")
    lines.append("")

    lines.append("---\n")
    lines.append(f"_Report generated at {datetime.now().isoformat()}_\n")
    return "\n".join(lines)


def main() -> None:
    start_ts: str = datetime.now().isoformat()
    t0: float = time.time()

    region_stats: dict[str, dict[str, float]] = load_json(REGION_STATS_PATH)
    monthly_trend: dict[str, dict[str, float]] = load_json(MONTHLY_TREND_PATH)

    report: str = generate_report(region_stats, monthly_trend)

    with open(REPORT_PATH, "w") as f:
        f.write(report)

    elapsed: float = time.time() - t0

    print(f"Report written → {REPORT_PATH}")
    print(f"Elapsed: {elapsed:.2f}s")
    print(f"\n--- Report Preview ---\n{report[:500]}...\n")

    # Log entry
    log_entry: str = (
        f"# Step C: Merge Report\n\n"
        f"| Field | Value |\n"
        f"|------|-------|\n"
        f"| **Timestamp** | {start_ts} |\n"
        f"| **Status** | Completed |\n"
        f"| **Input B1** | {REGION_STATS_PATH} |\n"
        f"| **Input B2** | {MONTHLY_TREND_PATH} |\n"
        f"| **Output** | {REPORT_PATH} |\n"
        f"| **Elapsed** | {elapsed:.2f}s |\n\n"
        f"## Key Decisions\n"
        f"1. Markdown format for human readability\n"
        f"2. Combined region stats and monthly trend into single report\n"
        f"3. Added Highlights section for quick insights\n"
        f"4. Clear separation of overview, region, and monthly sections\n"
    )
    print(f"\n--- Log ---\n{log_entry}")


if __name__ == "__main__":
    main()
